# Beryllium base

spacing         = 3
hide_ascii      = true
key_color       = "#7aa2f7"
separator       = ""

[box]
color           = "#f8f8f2"
border          = "rounded"
visible         = true

[palette]
glyph           = " ● "
visible         = true

[bar]
glyph           = "●"
hide_delimiters = false
visible         = false

[box.inner_margin]
x               = 2
y               = 1
